CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    dick INTEGER NOT NULL,
    countchoice INTEGER NOT NULL,
    avatar BLOB DEFAULT NULL,
    time INTEGER NOT NULL
);